version: "3"

services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    env_file:
      - .env
    depends_on:
      - database

volumes:
  db-volume:
