name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs_on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: "postgres://postgres:1387@database:5432/studentsACD_test"
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "1387"
          envkey_POSTGRES_DB: "studentsACD_test"
          file_name: ".env.test"
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run app npm run test
